"""
GLEIF reference code-list lookups — resolve the codes stored in LEI-CDF records to
human-readable names, the way gleif.org displays them:

- **ELF** (ISO 20275 Entity Legal Form): `EntityLegalFormCode` (e.g. `H0PO`) → a legal
  form name (e.g. "Private Limited Company").
- **RA** (GLEIF Registration Authorities): `RegistrationAuthorityID` (e.g. `RA000585`)
  → the register's name (e.g. "Companies Register"), the countries it serves, and —
  the part that matters for identity — `make_register_id()`, which turns
  (RA code, register number) into the graph's fifth hard identifier.

The lists are small, static reference data published by GLEIF separately from the
golden copy, bundled as compact JSON under `data/`. `gleif_elf.json` is flat
code → name; `gleif_ra.json` is code → {"name", "countries"} and is regenerated by
`scripts/build_gleif_ra_bundle.py` from GLEIF's published CSV
(https://www.gleif.org/en/lei-data/code-lists/gleif-registration-authorities-list).
"""
import functools
import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

_DATA = Path(__file__).parent / "data"

# Placeholder codes GLEIF assigns when there is NO real register behind a record:
# RA777777 = registered by public legal documents (governments, international
# orgs), RA888888 = temporary code while a new RA code is requested, RA999999 =
# no registration authority available (self-registered). Their "numbers" are not
# drawn from any shared namespace, so two unrelated self-registered companies
# both numbered "123" would merge on them. The bundle generator already drops
# them (no register name), but the guard here must not depend on a fresh bundle.
_EXCLUDED_RA = frozenset({"RA777777", "RA888888", "RA999999"})


@functools.lru_cache(maxsize=1)
def _load(name: str) -> dict:
    try:
        return json.loads((_DATA / name).read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:  # missing/corrupt bundle — degrade to codes
        log.warning("GLEIF reference list %s unavailable: %s", name, exc)
        return {}


def legal_form_name(code: str | None) -> str | None:
    """ELF code → legal form name, or None if the code is unknown/empty."""
    return _load("gleif_elf.json").get(code) if code else None


def registration_authority_name(code: str | None) -> str | None:
    """Registration Authority code → register name, or None if unknown/empty."""
    entry = _load("gleif_ra.json").get(code) if code else None
    if isinstance(entry, dict):
        return entry.get("name")
    return entry  # a stale flat bundle maps code → name directly; degrade, not crash


@functools.lru_cache(maxsize=1)
def _sole_registers() -> dict[str, str]:
    """country ISO-2 → RA code, only for countries served by exactly ONE register."""
    counts: dict[str, list[str]] = {}
    for code, entry in _load("gleif_ra.json").items():
        if not isinstance(entry, dict):
            continue  # stale flat bundle has no country data — map stays empty
        for country in entry.get("countries") or []:
            counts.setdefault(country, []).append(code)
    return {country: codes[0] for country, codes in counts.items() if len(codes) == 1}


def sole_register_for_country(iso2: str | None) -> str | None:
    """The country's RA code iff it has exactly one register, else None.

    This is what lets a source that states only a COUNTRY (Companies House PSC
    "country_registered", an OpenCorporates jurisdiction) contribute a
    `register_id`: unambiguous by construction. Countries with several registers
    (GB has 16, DE has 177 per-court ones sharing HRB numbering) return None —
    a bare country+number key would merge different companies there.
    """
    return _sole_registers().get(iso2.strip().upper()) if iso2 else None


# USPS abbreviations → the jurisdiction names GLEIF's RA list uses. Static on
# purpose: the 50 states + DC are not going anywhere, and the table is what
# lets an OpenCorporates "us_de" and a PSC "Delaware" land on the same key.
_US_STATES = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "FL": "Florida", "GA": "Georgia", "HI": "Hawaii", "ID": "Idaho",
    "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas",
    "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
    "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota",
    "MS": "Mississippi", "MO": "Missouri", "MT": "Montana", "NE": "Nebraska",
    "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey",
    "NM": "New Mexico", "NY": "New York", "NC": "North Carolina",
    "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma", "OR": "Oregon",
    "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
    "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah",
    "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
    "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming",
    "DC": "District Of Columbia",
}
_US_STATE_NAMES = {v.casefold(): v for v in _US_STATES.values()}

# The CURATED half of the map: jurisdictions where GLEIF lists several
# registers and the general corporate register must be picked by hand over the
# sector registries (insurance, credit unions, charities, trust companies).
# Verified against the 2024-11-20 RA list; extend only with the same check.
_PLACE_OVERRIDES = {
    ("US", "illinois"):   "RA000608",  # Business Services, not the License List
    ("US", "new york"):   "RA000628",  # Corporation Database, not insurance/charities
    ("US", "texas"):      "RA000637",  # Corporations Section, not credit unions/trusts
    ("US", "washington"): "RA000641",  # Corporations Division, not Business Lookup
}


# Countries whose jurisdiction scheme has been AUDITED for this map. The
# exactly-one rule alone is a trap: Bavaria's only listed register is a
# Foundations Directory, so a German PSC saying "Bavaria" plus an HRB number
# would mint a register_id on a sector registry that never issued it. A
# country joins this set only after checking that its listed jurisdictions
# are general corporate registers (US: 52 jurisdictions, all Secretary-of-
# State-class, 4 needing the overrides above).
_PLACE_COUNTRIES = {"US"}


@functools.lru_cache(maxsize=1)
def _place_registers() -> dict:
    """(country ISO-2, jurisdiction casefolded) → RA code — exactly-one, audited
    countries only."""
    counts: dict = {}
    for code, entry in _load("gleif_ra.json").items():
        if not isinstance(entry, dict):
            continue  # stale flat bundle — map stays empty, feature degrades off
        for country in entry.get("countries") or []:
            if country not in _PLACE_COUNTRIES:
                continue
            for jur in entry.get("jurisdictions") or []:
                counts.setdefault((country, jur.casefold()), []).append(code)
    return {key: codes[0] for key, codes in counts.items() if len(codes) == 1}


def register_for_place(iso2: str | None, place: str | None) -> str | None:
    """A sub-national place name → its RA code, where that is unambiguous.

    The place-level counterpart of `sole_register_for_country`: "USA" names 64
    registers, but "Delaware" names exactly one — so a source stating the
    STATE can contribute a register_id even though the country never could.
    Accepts the forms sources actually use: the jurisdiction name ("Delaware"),
    "State of X", a trailing country ("Delaware, USA"), or a USPS abbreviation
    ("DE", the OpenCorporates us_de form). A recognised US state name implies
    the country when the caller could not resolve one — "Delaware" in a PSC's
    country_registered field IS the country statement. Curated overrides pick
    the general corporate register for the four states where GLEIF lists
    sector registries beside it; everything else must be exactly-one.
    """
    norm = " ".join((place or "").replace(",", " ").split())
    if not norm:
        return None
    low = norm.casefold()
    for prefix in ("state of ", "the state of "):
        if low.startswith(prefix):
            low = low[len(prefix):]
    for suffix in (" usa", " united states", " united states of america", " us"):
        if low.endswith(suffix):
            low = low[: -len(suffix)].strip()
    if len(low) == 2 and low.upper() in _US_STATES:
        low = _US_STATES[low.upper()].casefold()
    country = (iso2 or "").strip().upper() or None
    if country is None and low in _US_STATE_NAMES:
        country = "US"
    if country is None:
        return None
    return (_PLACE_OVERRIDES.get((country, low))
            or _place_registers().get((country, low)))


def make_register_id(code: str | None, number: str | None) -> str | None:
    """(RA code, register number) → the `register_id` hard identifier, or None.

    Conservative on purpose — a missing key is safe, a wrong merge key is not:
    - both parts required; the placeholder codes above never qualify;
    - the code is uppercased (it is an enum);
    - ALL whitespace is removed from the number ("HRB 12345" and "HRB12345" are
      the same registration), but case and leading zeros are preserved — both
      are significant in some registers (Swiss numbers are zero-padded).
    """
    ra = (code or "").strip().upper()
    num = "".join((number or "").split())
    if not ra or not num or ra in _EXCLUDED_RA:
        return None
    return f"{ra}:{num}"
