"""
GLEIF reference code-list lookups — resolve the codes stored in LEI-CDF records to
human-readable names, the way gleif.org displays them:

- **ELF** (ISO 20275 Entity Legal Form): `EntityLegalFormCode` (e.g. `H0PO`) → a legal
  form name (e.g. "Private Limited Company").
- **RA** (GLEIF Registration Authorities): `RegistrationAuthorityID` (e.g. `RA000585`)
  → the register's name (e.g. "Companies Register"), the countries it serves, and —
  the part that matters for identity — `make_register_id()`, which turns
  (RA code, register number) into the graph's fifth hard identifier.

The lists are small, static reference data published by GLEIF separately from the
golden copy, bundled as compact JSON under `data/`. `gleif_elf.json` is flat
code → name; `gleif_ra.json` is code → {"name", "countries"} and is regenerated by
`scripts/build_gleif_ra_bundle.py` from GLEIF's published CSV
(https://www.gleif.org/en/lei-data/code-lists/gleif-registration-authorities-list).
"""
import functools
import json
import logging
import re
import unicodedata
from pathlib import Path

log = logging.getLogger(__name__)

_DATA = Path(__file__).parent / "data"

# Placeholder codes GLEIF assigns when there is NO real register behind a record:
# RA777777 = registered by public legal documents (governments, international
# orgs), RA888888 = temporary code while a new RA code is requested, RA999999 =
# no registration authority available (self-registered). Their "numbers" are not
# drawn from any shared namespace, so two unrelated self-registered companies
# both numbered "123" would merge on them. The bundle generator already drops
# them (no register name), but the guard here must not depend on a fresh bundle.
_EXCLUDED_RA = frozenset({"RA777777", "RA888888", "RA999999"})


@functools.lru_cache(maxsize=1)
def _load(name: str) -> dict:
    try:
        return json.loads((_DATA / name).read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:  # missing/corrupt bundle — degrade to codes
        log.warning("GLEIF reference list %s unavailable: %s", name, exc)
        return {}


def legal_form_name(code: str | None) -> str | None:
    """ELF code → legal form name, or None if the code is unknown/empty."""
    return _load("gleif_elf.json").get(code) if code else None


def registration_authority_name(code: str | None) -> str | None:
    """Registration Authority code → register name, or None if unknown/empty."""
    entry = _load("gleif_ra.json").get(code) if code else None
    if isinstance(entry, dict):
        return entry.get("name")
    return entry  # a stale flat bundle maps code → name directly; degrade, not crash


@functools.lru_cache(maxsize=1)
def _sole_registers() -> dict[str, str]:
    """country ISO-2 → RA code, only for countries served by exactly ONE register."""
    counts: dict[str, list[str]] = {}
    for code, entry in _load("gleif_ra.json").items():
        if not isinstance(entry, dict):
            continue  # stale flat bundle has no country data — map stays empty
        for country in entry.get("countries") or []:
            counts.setdefault(country, []).append(code)
    return {country: codes[0] for country, codes in counts.items() if len(codes) == 1}


def sole_register_for_country(iso2: str | None) -> str | None:
    """The country's RA code iff it has exactly one register, else None.

    This is what lets a source that states only a COUNTRY (Companies House PSC
    "country_registered", an OpenCorporates jurisdiction) contribute a
    `register_id`: unambiguous by construction. Countries with several registers
    (GB has 16, DE has 177 per-court ones sharing HRB numbering) return None —
    a bare country+number key would merge different companies there.
    """
    return _sole_registers().get(iso2.strip().upper()) if iso2 else None


# USPS abbreviations → the jurisdiction names GLEIF's RA list uses. Static on
# purpose: the 50 states + DC are not going anywhere, and the table is what
# lets an OpenCorporates "us_de" and a PSC "Delaware" land on the same key.
_US_STATES = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "FL": "Florida", "GA": "Georgia", "HI": "Hawaii", "ID": "Idaho",
    "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas",
    "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
    "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota",
    "MS": "Mississippi", "MO": "Missouri", "MT": "Montana", "NE": "Nebraska",
    "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey",
    "NM": "New Mexico", "NY": "New York", "NC": "North Carolina",
    "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma", "OR": "Oregon",
    "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina",
    "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas", "UT": "Utah",
    "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
    "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming",
    "DC": "District Of Columbia",
}
_US_STATE_NAMES = {v.casefold(): v for v in _US_STATES.values()}

# The CURATED half of the map: jurisdictions where GLEIF lists several
# registers and the general corporate register must be picked by hand over the
# sector registries (insurance, credit unions, charities, trust companies).
# Verified against the 2024-11-20 RA list; extend only with the same check.
_PLACE_OVERRIDES = {
    ("US", "illinois"):   "RA000608",  # Business Services, not the License List
    ("US", "new york"):   "RA000628",  # Corporation Database, not insurance/charities
    ("US", "texas"):      "RA000637",  # Corporations Section, not credit unions/trusts
    ("US", "washington"): "RA000641",  # Corporations Division, not Business Lookup
}


# Countries whose jurisdiction scheme has been AUDITED for this map. The
# exactly-one rule alone is a trap: Bavaria's only listed register is a
# Foundations Directory, so a German PSC saying "Bavaria" plus an HRB number
# would mint a register_id on a sector registry that never issued it. A
# country joins this set only after checking that its listed jurisdictions
# are general corporate registers (US: 52 jurisdictions, all Secretary-of-
# State-class, 4 needing the overrides above).
_PLACE_COUNTRIES = {"US"}


@functools.lru_cache(maxsize=1)
def _place_registers() -> dict:
    """(country ISO-2, jurisdiction casefolded) → RA code — exactly-one, audited
    countries only."""
    counts: dict = {}
    for code, entry in _load("gleif_ra.json").items():
        if not isinstance(entry, dict):
            continue  # stale flat bundle — map stays empty, feature degrades off
        for country in entry.get("countries") or []:
            if country not in _PLACE_COUNTRIES:
                continue
            for jur in entry.get("jurisdictions") or []:
                counts.setdefault((country, jur.casefold()), []).append(code)
    return {key: codes[0] for key, codes in counts.items() if len(codes) == 1}


def register_for_place(iso2: str | None, place: str | None) -> str | None:
    """A sub-national place name → its RA code, where that is unambiguous.

    The place-level counterpart of `sole_register_for_country`: "USA" names 64
    registers, but "Delaware" names exactly one — so a source stating the
    STATE can contribute a register_id even though the country never could.
    Accepts the forms sources actually use: the jurisdiction name ("Delaware"),
    "State of X", a trailing country ("Delaware, USA"), or a USPS abbreviation
    ("DE", the OpenCorporates us_de form). A recognised US state name implies
    the country when the caller could not resolve one — "Delaware" in a PSC's
    country_registered field IS the country statement. Curated overrides pick
    the general corporate register for the four states where GLEIF lists
    sector registries beside it; everything else must be exactly-one.
    """
    norm = " ".join((place or "").replace(",", " ").split())
    if not norm:
        return None
    low = norm.casefold()
    for prefix in ("state of ", "the state of "):
        if low.startswith(prefix):
            low = low[len(prefix):]
    for suffix in (" usa", " united states", " united states of america", " us"):
        if low.endswith(suffix):
            low = low[: -len(suffix)].strip()
    if len(low) == 2 and low.upper() in _US_STATES:
        low = _US_STATES[low.upper()].casefold()
    country = (iso2 or "").strip().upper() or None
    if country is None and low in _US_STATE_NAMES:
        country = "US"
    if country is None:
        return None
    hit = (_PLACE_OVERRIDES.get((country, low))
           or _place_registers().get((country, low)))
    if hit or country != "US":
        return hit
    # "Delaware Division Of Corporations", "Sunbiz Florida", "Delaware
    # Secretary Of State": the state's name inside the filer's words, when
    # exactly one state is named.
    padded = f" {low} "
    named = [st for st in _US_STATE_NAMES if f" {st} " in padded]
    if len(named) == 1:
        return _PLACE_OVERRIDES.get((country, named[0])) or _place_registers().get((country, named[0]))
    return None


#: Registers a NUMBER FORMAT identifies where the country alone names several.
#: Japan lists four RAs, but GLEIF itself files the Legal Affairs Bureau company
#: registration number (会社法人等番号, "0104-01-056795") under RA000412 and the
#: 13-digit corporate number (法人番号) under RA001075 — audited on the dev graph:
#: every dashed number sits under RA000412, none elsewhere. SoftBank Group's PSC
#: record carried that dashed number and stayed a name-only twin of its LEI node.
#: (country, format, RA code, canonical form of a matching number). Switzerland
#: likewise lists four RAs; a `CHE-105.909.036` UID is the Commercial Register's
#: form — all 24 Swiss GLEIF nodes on dev carry exactly that shape under
#: RA000549. Filers write the prefix as "Che-", GLEIF as "CHE-": uppercase it.
_NUMBER_FORMAT_REGISTERS = (
    ("JP", re.compile(r"\d{4}-\d{2}-\d{6}"), "RA000412", None),
    ("CH", re.compile(r"CHE-\d{3}\.\d{3}\.\d{3}", re.IGNORECASE), "RA000549", str.upper),
)


def register_for_number_format(iso2: str | None, number: str | None) -> str | None:
    """The RA code a registration number's FORMAT names, where audited.

    The third way to a `register_id` beside the sole-register country and the
    place map: for countries whose registers issue distinguishable formats, the
    number itself says which register issued it. Whitespace-insensitive like
    `make_register_id`; the format must match the whole number.
    """
    rule = _number_format_rule(iso2, number)
    return rule[2] if rule else None


def canonical_register_number(iso2: str | None, number: str | None) -> str | None:
    """The number as the register writes it, when a format rule matched — else
    the number unchanged. `make_register_id` preserves case on purpose (it is
    significant in some registers); a format rule knows its own register's
    spelling, so "Che-105.909.036" becomes the "CHE-105.909.036" GLEIF carries."""
    rule = _number_format_rule(iso2, number)
    if rule and rule[3]:
        return rule[3]("".join((number or "").split()))
    return number


def _number_format_rule(iso2: str | None, number: str | None):
    country = (iso2 or "").strip().upper()
    compact = "".join((number or "").split())
    if not country or not compact:
        return None
    for rule in _NUMBER_FORMAT_REGISTERS:
        if rule[0] == country and rule[1].fullmatch(compact):
            return rule
    return None


#: Words that name no register on their own — "Commercial Register" is what
#: 176 German courts are called. A match must carry at least one other word.
_GENERIC_WORDS = frozenset(
    "register registry registrar registration registers commercial company companies "
    "business trade enterprise enterprises office authority national central state "
    "public general court local federal ministry department division of the and for "
    "de du des la le les für der die das van het en et y e a".split())


def _singular(token: str) -> str:
    """companies → company, registries → registry, societes → societe: a filer's
    plural and the list's singular are the same word."""
    if len(token) > 4 and token.endswith("ies"):
        return token[:-3] + "y"
    if len(token) > 4 and token.endswith("s") and not token.endswith("ss"):
        return token[:-1]
    return token


#: Connectives that "Securities & Investments Commission" and "Securities and
#: Investments Commission" differ by — dropped before names are compared.
_STOP_WORDS = frozenset("and the of for de du des la le les et en van het und der die das y e a".split())


def _name_tokens(text: str | None) -> frozenset:
    folded = unicodedata.normalize("NFKD", text or "").encode("ascii", "ignore").decode()
    return frozenset(_singular(t) for t in re.split(r"[^a-z0-9]+", folded.casefold())
                     if t and t not in _STOP_WORDS)


#: What filers write that GLEIF's list does not: abbreviations and the name of
#: an organisation that runs several registers, resolved to the register a
#: company (a PSC controller) is on. From a survey of the 87,057 foreign
#: corporate controllers in the 2026-09 PSC snapshot; each line cites the
#: phrasing that needed it.
_REGISTER_ALIASES = {
    ("JE", "jfsc"): "RA000414",                    # "Jfsc Companies Registry" (1,091)
    ("JE", "jersey registry"): "RA000414",         # (150)
    ("JE", "jersey financial services commission"): "RA000414",   # (700) — also names the funds list
    ("GG", "guernsey registry"): "RA000383",       # (857) runs four registers; companies is the one
    ("GG", "guernsey register"): "RA000383",       # (114)
    ("GG", "guernsey companies registry"): "RA000383",   # (84)
    ("HK", "registrar of companies"): "RA000388",  # "Registrar Of Companies Hong Kong" (22)
    ("AU", "asic"): "RA000014",                    # (169) runs the companies and the licensees registers
    ("AU", "australian securities and investments commission"): "RA000014",   # (295 + variants)
    ("FR", "rcs"): "RA000192",                     # "Rcs Paris" (97), "Rcs Nanterre" (73); folds to Sirene
    ("LU", "rcs"): "RA000432",                     # "Rcs Luxembourg" (39)
    ("IE", "cro"): "RA000402",                     # (142)
    ("SE", "bolagsverket"): "RA000544",
    ("NL", "kvk"): "RA000463",
}


@functools.lru_cache(maxsize=1)
def _register_names() -> dict:
    """country → [(code, name-token-set, is_site)] for every register name and
    site domain in the bundle — the vocabulary `register_for_name` matches."""
    out: dict = {}
    for code, entry in _load("gleif_ra.json").items():
        if not isinstance(entry, dict):
            continue
        aliases = [(_name_tokens(n), "name") for n in entry.get("names") or [entry.get("name") or ""]]
        site = entry.get("site")
        if site:
            aliases.append((_name_tokens(site.split(".")[0]), "site"))   # "kvk" of kvk.nl
        for country in entry.get("countries") or []:
            out.setdefault(country, []).extend((code, toks, kind) for toks, kind in aliases if toks)
    for (country, alias), code in _REGISTER_ALIASES.items():
        out.setdefault(country, []).append((code, _name_tokens(alias), "alias"))
    return out


@functools.lru_cache(maxsize=None)
def _country_words(iso2: str) -> frozenset:
    from app.scraper.bulk_import import _ISO2_COUNTRY
    words = set(_name_tokens(_ISO2_COUNTRY.get(iso2, ""))) | {iso2.lower()}
    words |= {_singular(w) for w in _DEMONYMS.get(iso2, ())}
    return frozenset(words)


#: "Swiss Law", "German Company Law", "Companies Act 2014": words that add
#: nothing to which register is meant.
_NOISE_WORDS = frozenset("law act code ordinance regulation regulations statute legislation".split())

#: How filers write the country as an adjective — "Swiss Law", "Irish", "Dutch".
_DEMONYMS = {
    "CH": ("swiss", "switzerland"), "IE": ("irish",), "NL": ("dutch", "netherland"),
    "DE": ("german",), "FR": ("french",), "SE": ("swedish",), "JP": ("japanese",),
    "AU": ("australian",), "LU": ("luxembourgish",), "IT": ("italian",), "ES": ("spanish",),
    "DK": ("danish",), "NO": ("norwegian",), "FI": ("finnish",), "BE": ("belgian",),
    "AT": ("austrian",), "US": ("usa", "american", "united", "state"), "CA": ("canadian",),
    "HK": ("hong", "kong"), "SG": ("singaporean",), "GG": ("guernsey",), "JE": ("jersey",),
    "GB": ("uk", "british", "britain", "england", "english", "wales", "welsh", "scotland",
           "scottish", "northern", "ireland", "kingdom"),
    "IM": ("isle", "man", "manx"), "KY": ("cayman", "island"), "VG": ("british", "virgin", "island", "bvi"),
    "CY": ("cypriot",), "AE": ("emirate", "uae", "dubai"), "CN": ("chinese", "prc"), "IN": ("indian",),
}


def register_for_name(iso2: str | None, text: str | None) -> str | None:
    """The register a filer NAMED, where exactly one of the country's registers
    fits the words — the first thing to try, before any guess by country.

    A PSC record's `place_registered` / `legal_authority` is free text, but it
    usually is the register's name in the filer's language: "Kamer van
    Koophandel", "Firmenbuch", "Registre de Commerce et des Sociétés", "CSSF".
    GLEIF's list carries every register's international and local names, its
    organisation's names and its site, so the words can be matched — and this
    keys funds as well as companies, since a filer naming the CSSF gets the
    CSSF register. Matching, accent- and case-folded, by word sets:
    the whole name (best), the register's name inside the text, or the text
    inside the name (an abbreviation — "CSSF" in "CSSF - Supervised Entities").
    Generic words alone ("Commercial Register" — 176 German courts) never
    match, and two registers fitting equally well means no answer.
    """
    country = (iso2 or "").strip().upper()
    tokens = _name_tokens(text)
    if not country or not tokens:
        return None
    # "Netherlands", "Swiss", "Irish Law": the country's own name names no
    # register, and must not ride along as a match of "The Netherlands Chamber
    # of Commerce". Only country words (plus "law" and the like) → no answer;
    # the specific remainder is what an abbreviation match must rest on.
    specific = tokens - _GENERIC_WORDS - _country_words(country) - _NOISE_WORDS
    scores: dict[str, int] = {}
    for code, alias, kind in _register_names().get(country, ()):
        if alias == tokens:
            score = 4 if kind == "alias" else 3      # a curated alias is deliberate: it wins a tie
        elif alias <= tokens and kind != "site":
            score = 2                                # the register's name inside the filer's words
        elif tokens <= alias and specific:
            score = 1                                # an abbreviation or a part of the name
        else:
            continue
        scores[code] = max(scores.get(code, 0), score)
    if not scores:
        return None
    best = max(scores.values())
    winners = [c for c, sc in scores.items() if sc == best]
    if len(winners) == 1:
        return winners[0]
    # One organisation, several registers — Ireland's Companies Registration
    # Office runs the companies register and the friendly-societies one. The
    # filer means the register the country's companies are on, when the
    # audit knows which that is.
    general = general_register_for_country(country)
    return general if general in winners else None


@functools.lru_cache(maxsize=1)
def _general_registers() -> dict:
    """country ISO-2 → the register GLEIF's own GENERAL entities sit on nearly
    every time, from `general_registers.json` (see `register_audit`). Absent
    file or a stale shape → empty map; the feature degrades to the other rules."""
    try:
        data = _load("general_registers.json")
    except Exception:  # noqa: BLE001 - data file optional
        return {}
    countries = data.get("countries") if isinstance(data, dict) else None
    return {c: e["code"] for c, e in (countries or {}).items()
            if isinstance(e, dict) and e.get("code")}


def general_register_for_country(iso2: str | None) -> str | None:
    """The country's general corporate register, where the audit found one.

    The last resort after the sole-register rule, the place map and the
    number-format rules: the RA table lists four registers for the
    Netherlands, but 100% of Dutch GENERAL entities on GLEIF sit on the KVK
    (RA000463) — the other three are sector registries a company would never
    file a PSC number from. Countries where no register clearly dominates
    (Germany per court, the US and Canada per state) are not in the map.
    """
    return _general_registers().get(iso2.strip().upper()) if iso2 else None


@functools.lru_cache(maxsize=1)
def _zero_insensitive_ras() -> frozenset:
    """The audited US state registers, where a purely numeric filing number's
    leading zeros are formatting, not identity: GLEIF publishes Tesla's Texas
    number as 0805587591, the Companies House filer wrote 805587591, and both
    name the same registration. Exactly the place-map scope — the same audit
    that vouched for the registers vouches for their numbering."""
    return frozenset(_place_registers().values()) | frozenset(_PLACE_OVERRIDES.values())


def make_register_id(code: str | None, number: str | None) -> str | None:
    """(RA code, register number) → the `register_id` hard identifier, or None.

    Conservative on purpose — a missing key is safe, a wrong merge key is not:
    - both parts required; the placeholder codes above never qualify;
    - the code is uppercased (it is an enum);
    - ALL whitespace is removed from the number ("HRB 12345" and "HRB12345" are
      the same registration), but case and leading zeros are preserved — both
      are significant in some registers (Swiss numbers are zero-padded) — EXCEPT
      for the audited US state registers, where sources demonstrably disagree
      on zero-padding of what is a plain integer (see _zero_insensitive_ras).
    """
    ra = (code or "").strip().upper()
    num = "".join((number or "").split())
    if not ra or not num or ra in _EXCLUDED_RA:
        return None
    if num.isdigit() and ra in _zero_insensitive_ras():
        num = num.lstrip("0") or "0"
    ra = _REGISTER_FOLDS.get(ra, ra)
    style = _NUMBER_STYLES.get(ra)
    if style:
        num = style(num)
    return f"{ra}:{num}"


def _swiss_uid(num: str) -> str:
    """CHE105909036 / Che-105.909.036 → CHE-105.909.036, the UID's official form."""
    m = re.fullmatch(r"(?i)CHE[-‑]?(\d{3})\.?(\d{3})\.?(\d{3})", num)
    return f"CHE-{m.group(1)}.{m.group(2)}.{m.group(3)}" if m else num


def _digits_only(num: str) -> str:
    """0402.231.383 → 0402231383: separators are typography, not identity."""
    return num.replace(".", "") if re.fullmatch(r"[\d.]+", num) else num


#: Registers that carry ONE national number under two codes — audited on the
#: full golden copy (2026-09-20): the Swiss UID sits under the UID register
#: (RA000548, 55%) and the Commercial Register (RA000549, 45%), written
#: CHE105909036 and CHE-105.909.036; the French SIREN under Sirene (RA000189,
#: 95%) and the RCS (RA000192, 5%). Two keys for one number is no key at all,
#: so both fold to one code — the Commercial Register for Switzerland (the
#: register of record; what every earlier node carries), Sirene for France.
_REGISTER_FOLDS = {"RA000548": "RA000549", "RA000192": "RA000189"}

#: One spelling per register where GLEIF itself uses several for one number.
_NUMBER_STYLES = {
    "RA000549": _swiss_uid,          # Swiss UID
    "RA000189": _digits_only,        # SIREN, occasionally "542 014 428"
    "RA000025": _digits_only,        # Belgian KBO: 0402.231.383 and 0402231383
}
