"""
GLEIF reference code-list lookups — resolve the codes stored in LEI-CDF records to
human-readable names, the way gleif.org displays them:

- **ELF** (ISO 20275 Entity Legal Form): `EntityLegalFormCode` (e.g. `H0PO`) → a legal
  form name (e.g. "Private Limited Company").
- **RA** (GLEIF Registration Authorities): `RegistrationAuthorityID` (e.g. `RA000585`)
  → the register's name (e.g. "Companies Register"), the countries it serves, and —
  the part that matters for identity — `make_register_id()`, which turns
  (RA code, register number) into the graph's fifth hard identifier.

The lists are small, static reference data published by GLEIF separately from the
golden copy, bundled as compact JSON under `data/`. `gleif_elf.json` is flat
code → name; `gleif_ra.json` is code → {"name", "countries"} and is regenerated by
`scripts/build_gleif_ra_bundle.py` from GLEIF's published CSV
(https://www.gleif.org/en/lei-data/code-lists/gleif-registration-authorities-list).
"""
import functools
import json
import logging
from pathlib import Path

log = logging.getLogger(__name__)

_DATA = Path(__file__).parent / "data"

# Placeholder codes GLEIF assigns when there is NO real register behind a record:
# RA777777 = registered by public legal documents (governments, international
# orgs), RA888888 = temporary code while a new RA code is requested, RA999999 =
# no registration authority available (self-registered). Their "numbers" are not
# drawn from any shared namespace, so two unrelated self-registered companies
# both numbered "123" would merge on them. The bundle generator already drops
# them (no register name), but the guard here must not depend on a fresh bundle.
_EXCLUDED_RA = frozenset({"RA777777", "RA888888", "RA999999"})


@functools.lru_cache(maxsize=1)
def _load(name: str) -> dict:
    try:
        return json.loads((_DATA / name).read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:  # missing/corrupt bundle — degrade to codes
        log.warning("GLEIF reference list %s unavailable: %s", name, exc)
        return {}


def legal_form_name(code: str | None) -> str | None:
    """ELF code → legal form name, or None if the code is unknown/empty."""
    return _load("gleif_elf.json").get(code) if code else None


def registration_authority_name(code: str | None) -> str | None:
    """Registration Authority code → register name, or None if unknown/empty."""
    entry = _load("gleif_ra.json").get(code) if code else None
    if isinstance(entry, dict):
        return entry.get("name")
    return entry  # a stale flat bundle maps code → name directly; degrade, not crash


@functools.lru_cache(maxsize=1)
def _sole_registers() -> dict[str, str]:
    """country ISO-2 → RA code, only for countries served by exactly ONE register."""
    counts: dict[str, list[str]] = {}
    for code, entry in _load("gleif_ra.json").items():
        if not isinstance(entry, dict):
            continue  # stale flat bundle has no country data — map stays empty
        for country in entry.get("countries") or []:
            counts.setdefault(country, []).append(code)
    return {country: codes[0] for country, codes in counts.items() if len(codes) == 1}


def sole_register_for_country(iso2: str | None) -> str | None:
    """The country's RA code iff it has exactly one register, else None.

    This is what lets a source that states only a COUNTRY (Companies House PSC
    "country_registered", an OpenCorporates jurisdiction) contribute a
    `register_id`: unambiguous by construction. Countries with several registers
    (GB has 16, DE has 177 per-court ones sharing HRB numbering) return None —
    a bare country+number key would merge different companies there.
    """
    return _sole_registers().get(iso2.strip().upper()) if iso2 else None


def make_register_id(code: str | None, number: str | None) -> str | None:
    """(RA code, register number) → the `register_id` hard identifier, or None.

    Conservative on purpose — a missing key is safe, a wrong merge key is not:
    - both parts required; the placeholder codes above never qualify;
    - the code is uppercased (it is an enum);
    - ALL whitespace is removed from the number ("HRB 12345" and "HRB12345" are
      the same registration), but case and leading zeros are preserved — both
      are significant in some registers (Swiss numbers are zero-padded).
    """
    ra = (code or "").strip().upper()
    num = "".join((number or "").split())
    if not ra or not num or ra in _EXCLUDED_RA:
        return None
    return f"{ra}:{num}"
